version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run: yarn install
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run: mkdir -p ./cucumber
      - run: yarn ci-test
      - store_test_results:
          path: ./cucumber
      - store_artifacts:
          path: ./cucumber
workflows:
  version: 2
  main:
    jobs:
      - build